adjective = input("adjective: ")
adjective2 = input("adjective: ")
bird = input("type of bird: ")
room = input("room in a house: ")
verb = input("verb(past tense): ")
verb2 = input("verb: ")
name= input("name: ")
noun = input("noun: ")
liq = input("liquid: ")
verb3 = input("verb ending with -ing: ")
part = input("body part(plural): ")
pnoun = input("plural noun: ")
verbing = input("verb ending with -ing: ")
noun2 = input("Noun: ")

story = print(f"It was a {adjective}, cold Novemeber day. I woke up to the {adjective2} smell of {bird} roasting in the {room} downstairs.\nI {verb} down the stairs to see if I could help {verb2} the dinner.\nMy mom said,'see if {name} needs a fresh {noun}'.\nSo I carried a tray of glasses full of {liq} into the {verb3} room.\nWhen i got there, I couldn't believe my {part}!\nThere were {pnoun} {verbing} on the {noun2}!.")